version: '3.8'

services:
  kg-db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kg-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  kg-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: kg-server
    restart: always
    ports:
      - '9081:9081'
    networks:
      - kg-network
    environment:
      - DATABASE_DRIVER_NAME=postgres
      - DATABASE_DATASOURCE=host=kg-db port=5432 user=postgres password=mysecretpassword dbname=postgres sslmode=disable
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SITE_URL=${SITE_URL}
    depends_on:
      - kg-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9081/healthcheck"]
      interval: 15s
      timeout: 15s
      start_period: 15s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  kg-webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: kg-webapp
    restart: always
    ports:
      - '9091:9091'
    environment:
      - KG_SERVER_URL_DOCKER=http://kg-server:9081
    stdin_open: true
    tty: true
    networks:
      - kg-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

networks:
  kg-network:
    driver: bridge

volumes:
  postgres-data:
