name: 'Docker Build'

on:
  push:
    branches: 'main'

jobs:
  Docker_Build:
    runs-on: 'ubuntu-22.04'
    name: 'Docker Build'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3.5.3'
      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v2.9.1'
      - name: 'Configure AWS credentials'
        uses: 'aws-actions/configure-aws-credentials@v2.2.0'
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: 'eu-central-1'
      - name: 'Login to Amazon ECR'
        uses: 'aws-actions/amazon-ecr-login@v1.6.2'
      - name: 'Cache Docker layers'
        uses: 'actions/cache@v3.3.1'
        with:
          path: '/tmp/.buildx-cache'
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: 'Build and push server app'
        uses: 'docker/build-push-action@v4.1.1'
        with:
          context: '.'
          file: './Dockerfile.server'
          pull: 'true'
          push: 'true'
          tags: 218502875136.dkr.ecr.eu-central-1.amazonaws.com/knowledge-graph-server:latest
          cache-from: 'type=local,src=/tmp/.buildx-cache'
          cache-to: 'type=local,dest=/tmp/.buildx-cache'
          platforms: linux/amd64
          labels: |
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=latest
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
      - name: Install webapp dependencies
        run: npm i --force
      - name: Build webapp
        run: make build-webapp
      - name: Upload public to S3 root (excluding index.html)
        run: |
          aws s3 sync webapp/public/ s3://vitsi-ai-bucket/ --exclude "index.html"
      - name: Upload /dist to S3 root
        run: |
          aws s3 sync webapp/dist/ s3://vitsi-ai-bucket/

