name: eslint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      working-directory: ./webapp
      run: npm i --force
    - name: Run ESLint
      working-directory: ./webapp
      run: npx eslint --ext .js,.jsx,.tsx,.ts . --quiet --cache
